FROM python:3.10.17-alpine3.21
ARG version="0.0"
ENV AIAS_VERSION=${version}

LABEL io.arlas.aproc-service.version=${version}
LABEL vendor="Gisaïa"
LABEL description="This container serves ARLAS APROC Service"

RUN apk update && apk add --upgrade libexpat

RUN apk --no-cache add curl

COPY ./aproc/requirements.txt /app/requirements.txt
COPY ./extensions/requirements.storage.txt /app/requirements.storage.txt

WORKDIR /app

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements.storage.txt

COPY ./aproc /app/aproc
COPY ./extensions /app/extensions
COPY ./airs/core/ /app/airs/core/
COPY ./aias_common /app/aias_common
COPY ./conf /app/conf
COPY ./scripts/aproc/start.sh /app/
COPY ./conf /app/conf

ENV APROC_CONFIGURATION_FILE=/app/conf/aproc.yaml
ENV PYTHONPATH=/app/

EXPOSE 8001
ENTRYPOINT ["./start.sh"]