FROM python:3.10.13-alpine3.19
ARG version="0.0"
ENV AIAS_VERSION=${version}

LABEL io.arlas.airs.version=${version}
LABEL vendor="Gisaïa"
LABEL description="This container serves ARLAS AIRS"

RUN apk update && apk add --upgrade libexpat

RUN apk --no-cache add curl

COPY ./airs/requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

COPY ./airs /app/airs
COPY ./aias_common /app/aias_common
COPY ./conf /app/conf
COPY ./scripts/airs/start.sh /app/

RUN curl "https://raw.githubusercontent.com/gisaia/ARLAS-EO/v0.0.9/mapping.json" -o ./conf/mapping.json
RUN curl "https://raw.githubusercontent.com/gisaia/ARLAS-EO/v0.0.9/collection.json" -o ./conf/collection.json

EXPOSE 8000
ENTRYPOINT ["./start.sh"]