FROM python:3.10.13-alpine3.19
RUN apk update && apk add --upgrade libexpat

RUN apk --no-cache add curl

COPY ./fam/requirements.txt /app/requirements.txt
COPY ./extensions/requirements.storage.txt /app/requirements.storage.txt

WORKDIR /app

RUN pip install -r requirements.txt
RUN pip install -r requirements.storage.txt

COPY ./aproc /app/aproc
COPY ./extensions /app/extensions
COPY ./fam /app/fam
COPY ./airs/core/models /app/airs/core/models
COPY ./airs/core/models/__init__.py /app/airs/core/models/__init__.py
COPY ./common /app/common
COPY ./conf/fam.yaml /app/conf/
COPY ./conf/drivers.yaml /app/conf/
COPY ./conf/aproc.yaml /app/conf/

COPY ./scripts/fam/start.sh /app/

EXPOSE 8005

ENV APROC_CONFIGURATION_FILE=/app/conf/aproc.yaml
ENV PYTHONPATH=PYTHONPATH=$PYTHONPATH:/app
ENTRYPOINT ["./start.sh"]
