FROM python:3.10.13-alpine3.19
ARG version="0.0"
ENV AIAS_VERSION=${version}

LABEL io.arlas.geodes-stac.version=${version}
LABEL vendor="Gisaïa"
LABEL description="This container serves ARLAS GEODES STAC Sync"

RUN apk update && apk add --upgrade libexpat
RUN apk --no-cache add curl
COPY requirements-stac.txt /app/requirements.txt
COPY ./extensions/requirements.storage.txt /app/requirements.storage.txt

WORKDIR /app

RUN pip3 install -r requirements.txt
RUN pip install -r requirements.storage.txt

COPY stac /app/stac
COPY ./airs /app/airs
COPY ./common /app/common
COPY ./extensions/aproc/proc/access /app/extensions/aproc/proc/access

ENV PYTHONPATH=/app

ENTRYPOINT ["python3.10", "-m", "stac.geodes_sync"]
