FROM python:3.10.17-alpine3.21
RUN pip3 install --no-cache-dir --upgrade pip setuptools

ARG version="0.0"
ENV AIAS_VERSION=${version}

LABEL io.arlas.airs.version=${version}
LABEL vendor="Gisaïa"
LABEL description="This container serves ARLAS AIRS"

RUN apk update && apk add --no-cache curl

RUN addgroup -g 1000 arlasgroup && \
    adduser -D -u 1000 -G arlasgroup arlasuser
USER 1000
WORKDIR /app

COPY --chown=arlasuser:arlasgroup ./airs/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY --chown=arlasuser:arlasgroup ./airs /app/airs
COPY --chown=arlasuser:arlasgroup ./aias_common /app/aias_common
COPY --chown=arlasuser:arlasgroup ./conf /app/conf
COPY --chown=arlasuser:arlasgroup ./scripts/airs/start.sh /app/

EXPOSE 8000
ENTRYPOINT ["./start.sh"]