version: "3"
networks:
  airs:
services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - airs
    environment:
      - "MINIO_ACCESS_KEY=airs"
      - "MINIO_SECRET_KEY=airssecret"
    command: server /export --console-address ":9001"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    environment:
      - BUCKET_NAME=${BUCKET_NAME:-airstest}
      - LOGIN=${LOGIN:-airs}
      - PASSWORD=${PASSWORD:-airssecret}
    networks:
      - airs
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 $$LOGIN $$PASSWORD;
      /usr/bin/mc rm -r --force myminio/$$BUCKET_NAME;
      /usr/bin/mc mb myminio/$$BUCKET_NAME;
      /usr/bin/mc anonymous set public myminio/$$BUCKET_NAME;
      exit 0;
      "
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-8.9.2}
    container_name: elasticsearch
    networks:
      - airs
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - node.name=docker-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - 9200:9200

  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION:-3-management}
    container_name: rabbitmq
    networks:
      - airs
    ports:
      - 15672:15672
      - 5672:5672

  redis:
    image: redis:${REDIS_VERSION:-7.2}
    networks:
      - airs
    container_name: redis
    ports:
      - 6379:6379

  aproc-processes:
    networks:
      - airs
    build:
      context: '.'
      dockerfile: Dockerfile-aproc
    image: aproc-processes:latest
    #command: tail -f /dev/null
    container_name: 'aproc-processes'
    environment:
      - APROC_CONFIGURATION_FILE=/home/app/worker/conf/aproc.yaml
      - CELERY_BROKER_URL=pyamqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - AIRS_ENDPOINT=http://airs-server:8000
      - ROOT_DIRECTORY=/inputs
    volumes:
      - ./test/inputs:/inputs
    depends_on:
      - redis
      - rabbitmq

  airs-server:
    networks:
      - airs
    build:
      context: '.'
      dockerfile: Dockerfile-airs
    image: airs-server:latest
    container_name: 'airs-server'
    environment:
      - AIRS_HOST=0.0.0.0
      - AIRS_PORT=8000
      - AIRS_INDEX_ENDPOINT_URL=${AIRS_INDEX_ENDPOINT_URL:-http://localhost:9200}
      - AIRS_INDEX_COLLECTION_PREFIX=${AIRS_INDEX_COLLECTION_PREFIX:-airs}
      - AIRS_INDEX_LOGIN=${AIRS_INDEX_LOGIN:-None}
      - AIRS_INDEX_PWD=${AIRS_INDEX_PWD:-None}
      - AIRS_S3_BUCKET=${AIRS_S3_BUCKET:-airstest}
      - AIRS_S3_ACCESS_KEY_ID=${AIRS_S3_ACCESS_KEY_ID}
      - AIRS_S3_SECRET_ACCESS_KEY=${AIRS_S3_SECRET_ACCESS_KEY}
      - AIRS_S3_REGION=${AIRS_S3_REGION:-None}
      - AIRS_S3_TIER=${AIRS_S3_TIER:-Standard}
      - AIRS_S3_PLATFORM=${AIRS_S3_PLATFORM}
      - AIRS_S3_ASSET_HTTP_ENDPOINT_URL=${AIRS_S3_ASSET_HTTP_ENDPOINT_URL}
      - AIRS_S3_ENDPOINT_URL=${AIRS_S3_ENDPOINT_URL}
      - AIRS_MAPPING_URL=${AIRS_MAPPING_URL:-https://raw.githubusercontent.com/gisaia/ARLAS-EO/v0.0.1/mapping.json}
      - AIRS_COLLECTION_URL=${AIRS_COLLECTION_URL:-https://raw.githubusercontent.com/gisaia/ARLAS-EO/v0.0.1/collection.json}
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
      - minio
