FROM python:3.10.17-alpine3.21
ARG version="0.0"
ENV AIAS_VERSION=${version}

LABEL io.arlas.fam.version=${version}
LABEL vendor="Gisaïa"
LABEL description="This container serves ARLAS APROC FAM"

RUN apk update && apk add --upgrade libexpat

RUN apk --no-cache add curl

RUN addgroup -g 1000 arlasgroup && \
    adduser -D -u 1000 -G arlasgroup arlasuser
USER 1000
WORKDIR /app

COPY --chown=arlasuser:arlasgroup ./fam/requirements.txt /app/requirements.txt
COPY --chown=arlasuser:arlasgroup ./extensions/requirements.storage.txt /app/requirements.storage.txt

RUN pip install --no-cache-dir -r requirements.txt -r requirements.storage.txt

COPY --chown=arlasuser:arlasgroup ./aproc /app/aproc
COPY --chown=arlasuser:arlasgroup ./extensions /app/extensions
COPY --chown=arlasuser:arlasgroup ./fam /app/fam
COPY --chown=arlasuser:arlasgroup ./airs/core/models /app/airs/core/models
COPY --chown=arlasuser:arlasgroup ./airs/core/models/__init__.py /app/airs/core/models/__init__.py
COPY --chown=arlasuser:arlasgroup ./aias_common /app/aias_common
COPY --chown=arlasuser:arlasgroup ./conf/fam.yaml /app/conf/
COPY --chown=arlasuser:arlasgroup ./conf/drivers.yaml /app/conf/
COPY --chown=arlasuser:arlasgroup ./conf/aproc.yaml /app/conf/

COPY --chown=arlasuser:arlasgroup ./scripts/fam/start.sh /app/

EXPOSE 8005

ENV APROC_CONFIGURATION_FILE=/app/conf/aproc.yaml
ENV PYTHONPATH=PYTHONPATH=$PYTHONPATH:/app
ENTRYPOINT ["./start.sh"]
