version: "3"
networks:
  aias:
services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - aias
    environment:
      - "MINIO_ACCESS_KEY=airs"
      - "MINIO_SECRET_KEY=airssecret"
    command: server /export --console-address ":9001"
    healthcheck:
      test: "mc alias set myminio http://localhost:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; mc ping -x myminio"
      interval: 5s
      timeout: 10s
      retries: 3

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-8.9.2}
    container_name: elasticsearch
    networks:
      - aias
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - node.name=docker-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - 9200:9200
    healthcheck:
      test: "curl -s -X GET http://localhost:9200/_cluster/health?pretty | grep status | grep -q '\\(green\\|yellow\\)'"
      interval: 10s
      timeout: 10s
      retries: 24

  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION:-3-management}
    container_name: rabbitmq
    networks:
      - aias
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10

  smtp4dev:
    image: rnwood/smtp4dev:linux-${PLATFORM}-3.2.0-ci20221023104
    platform: linux/${PLATFORM}
    container_name: smtp4dev
    networks:
      - aias
    ports:
      - 3000:80
    environment:
      #Specifies the server hostname. Used in auto-generated TLS certificate if enabled.
      - ServerOptions__HostName=smtp4dev

  redis:
    image: redis/redis-stack:${REDIS_VERSION:-7.2.0-v2}
    networks:
      - aias
    container_name: redis
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  airs-server:
    networks:
      - aias
    build:
      context: '.'
      dockerfile: Dockerfile-airs
    image: airs-server:latest
    container_name: 'airs-server'
    depends_on:
      elasticsearch:
        condition: service_healthy
      minio:
        condition: service_healthy
    environment:
      - AIRS_HOST=0.0.0.0
      - AIRS_PORT=8000
      - AIRS_CORS_ORIGINS=${AIRS_CORS_ORIGINS:-*}
      - AIRS_CORS_METHODS=${AIRS_CORS_METHODS:-*}
      - AIRS_CORS_HEADERS=${AIRS_CORS_HEADERS:-*}
      - AIRS_INDEX_ENDPOINT_URL=${AIRS_INDEX_ENDPOINT_URL:-http://localhost:9200}
      - AIRS_INDEX_COLLECTION_PREFIX=${AIRS_INDEX_COLLECTION_PREFIX:-airs}
      - AIRS_INDEX_LOGIN=${AIRS_INDEX_LOGIN:-None}
      - AIRS_INDEX_PWD=${AIRS_INDEX_PWD:-None}
      - AIRS_S3_BUCKET=${AIRS_S3_BUCKET:-airstest}
      - AIRS_S3_ACCESS_KEY_ID=${AIRS_S3_ACCESS_KEY_ID}
      - AIRS_S3_SECRET_ACCESS_KEY=${AIRS_S3_SECRET_ACCESS_KEY}
      - AIRS_S3_REGION=${AIRS_S3_REGION}
      - AIRS_S3_TIER=${AIRS_S3_TIER:-Standard}
      - AIRS_S3_PLATFORM=${AIRS_S3_PLATFORM}
      - AIRS_S3_ASSET_HTTP_ENDPOINT_URL=${AIRS_S3_ASSET_HTTP_ENDPOINT_URL}
      - AIRS_S3_ENDPOINT_URL=${AIRS_S3_ENDPOINT_URL}
      - ARLASEO_MAPPING_URL=${ARLASEO_MAPPING_URL:-https://raw.githubusercontent.com/gisaia/ARLAS-EO/v0.0.9/mapping.json}
      - AIRS_COLLECTION_URL=${AIRS_COLLECTION_URL:-https://raw.githubusercontent.com/gisaia/ARLAS-EO/v0.0.9/collection.json}
      - AIRS_LOGGER_LEVEL=${AIRS_LOGGER_LEVEL:-INFO}
      - DOWNLOAD_S3_ENDPOINT_URL=${DOWNLOAD_S3_ENDPOINT_URL:-http://minio:9000}
      - DOWNLOAD_S3_BUCKET=${DOWNLOAD_S3_BUCKET}
      - DOWNLOAD_S3_ACCESS_KEY_ID=${DOWNLOAD_S3_ACCESS_KEY_ID:-airs}
      - DOWNLOAD_S3_SECRET_ACCESS_KEY=${DOWNLOAD_S3_SECRET_ACCESS_KEY:-airssecret}
      - DOWNLOAD_S3_ASSET_HTTP_ENDPOINT_URL=${DOWNLOAD_S3_ASSET_HTTP_ENDPOINT_URL:-http://minio:9000/{}/{}}
    ports:
      - "8000:8000"
    healthcheck:
      test: "curl -f http://localhost:8000/arlas/airs/healthcheck"
      interval: 5s
      timeout: 3s
      retries: 30

  aproc-processes:
    networks:
      - aias
    build:
      context: '.'
      dockerfile: Dockerfile-aproc-proc
    image: aproc-processes:latest
    platform: linux/amd64
    #command: tail -f /dev/null
    container_name: 'aproc-processes'
    environment:
      - APROC_ENDPOINT_FROM_APROC=$APROC_ENDPOINT_FROM_APROC
      - ARLAS_URL_SEARCH=$ARLAS_URL_SEARCH
      - APROC_CONFIGURATION_FILE=/home/app/worker/conf/aproc.yaml
      - CELERY_BROKER_URL=pyamqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - AIRS_ENDPOINT=http://airs-server:8000/arlas/airs
      - AIRS_INDEX_COLLECTION_PREFIX=${AIRS_INDEX_COLLECTION_PREFIX:-airs}
      - ARLAS_SMTP_ACTIVATED=${ARLAS_SMTP_ACTIVATED}
      - ARLAS_SMTP_HOST=${ARLAS_SMTP_HOST}
      - ARLAS_SMTP_PORT=${ARLAS_SMTP_PORT}
      - ARLAS_SMTP_USERNAME=${ARLAS_SMTP_USERNAME}
      - ARLAS_SMTP_PASSWORD=${ARLAS_SMTP_PASSWORD}
      - ARLAS_SMTP_FROM=${ARLAS_SMTP_FROM}
      - APROC_DOWNLOAD_ADMIN_EMAILS=${APROC_DOWNLOAD_ADMIN_EMAILS}
      - APROC_DOWNLOAD_OUTBOX_DIR=${APROC_DOWNLOAD_OUTBOX_DIR}
      - APROC_DOWNLOAD_CONTENT_USER=${APROC_DOWNLOAD_CONTENT_USER}
      - APROC_DOWNLOAD_SUBJECT_USER=${APROC_DOWNLOAD_SUBJECT_USER}
      - APROC_DOWNLOAD_CONTENT_ERROR=${APROC_DOWNLOAD_CONTENT_ERROR}
      - APROC_DOWNLOAD_SUBJECT_ERROR=${APROC_DOWNLOAD_SUBJECT_ERROR}
      - APROC_DOWNLOAD_CONTENT_ADMIN=${APROC_DOWNLOAD_CONTENT_ADMIN}
      - APROC_DOWNLOAD_SUBJECT_ADMIN=${APROC_DOWNLOAD_SUBJECT_ADMIN}
      - APROC_EMAIL_PATH_PREFIX_ADD=${APROC_EMAIL_PATH_PREFIX_ADD}
      - APROC_PATH_TO_WINDOWS=${APROC_PATH_TO_WINDOWS}
      - APROC_DOWNLOAD_REQUEST_SUBJECT_USER=${APROC_DOWNLOAD_REQUEST_SUBJECT_USER}
      - APROC_DOWNLOAD_REQUEST_CONTENT_USER=${APROC_DOWNLOAD_REQUEST_CONTENT_USER}
      - APROC_DOWNLOAD_REQUEST_SUBJECT_ADMIN=${APROC_DOWNLOAD_REQUEST_SUBJECT_ADMIN}
      - APROC_DOWNLOAD_REQUEST_CONTENT_ADMIN=${APROC_DOWNLOAD_REQUEST_CONTENT_ADMIN}
      - APROC_INDEX_ENDPOINT_URL=${APROC_INDEX_ENDPOINT_URL}
      - APROC_INDEX_NAME=${APROC_INDEX_NAME}
      - APROC_INDEX_LOGIN=${APROC_INDEX_LOGIN:-None}
      - APROC_LOGGER_LEVEL=${APROC_LOGGER_LEVEL:-INFO}
      - APROC_INDEX_PWD=${APROC_INDEX_PWD:-None}
      - APROC_RESOURCE_ID_HASH_STARTS_AT=${APROC_RESOURCE_ID_HASH_STARTS_AT:-3}
      - TMP_FOLDER=${TMP_FOLDER:-/outbox}
      - DOWNLOAD_S3_ENDPOINT_URL=${DOWNLOAD_S3_ENDPOINT_URL:-http://minio:9000}
      - DOWNLOAD_S3_BUCKET=${DOWNLOAD_S3_BUCKET}
      - DOWNLOAD_S3_ACCESS_KEY_ID=${DOWNLOAD_S3_ACCESS_KEY_ID:-airs}
      - DOWNLOAD_S3_SECRET_ACCESS_KEY=${DOWNLOAD_S3_SECRET_ACCESS_KEY:-airssecret}
      - DOWNLOAD_S3_ASSET_HTTP_ENDPOINT_URL=${DOWNLOAD_S3_ASSET_HTTP_ENDPOINT_URL:-http://minio:9000/{}/{}}
      - CLEAN_DOWNLOAD_OUTBOX_DIR=${CLEAN_DOWNLOAD_OUTBOX_DIR:-True}
      - APROC_INPUT_STORAGE_TYPE=${APROC_INPUT_STORAGE_TYPE}
      - APROC_INPUT_STORAGE_BUCKET=${APROC_INPUT_STORAGE_BUCKET}
      - APROC_INPUT_STORAGE_API_KEY_PROJECT=${APROC_INPUT_STORAGE_API_KEY_PROJECT}
      - APROC_INPUT_STORAGE_API_KEY_PRIVATE_KEY_ID=${APROC_INPUT_STORAGE_API_KEY_PRIVATE_KEY_ID}
      - APROC_INPUT_STORAGE_API_KEY_PRIVATE_KEY=${APROC_INPUT_STORAGE_API_KEY_PRIVATE_KEY}
      - APROC_INPUT_STORAGE_HEADERS=${APROC_INPUT_STORAGE_HEADERS}
      - APROC_INPUT_STORAGE_DOMAIN=${APROC_INPUT_STORAGE_DOMAIN}
      - APROC_INPUT_STORAGE_FORCE_DOWNLOAD=${APROC_INPUT_STORAGE_FORCE_DOWNLOAD}
    volumes:
      - ./test/inputs:/inputs:ro
      - ./outbox/:/outbox
    depends_on:
      redis:
          condition: service_healthy
      rabbitmq:
          condition: service_healthy

  aproc-service:
    networks:
      - aias
    build:
      context: '.'
      dockerfile: Dockerfile-aproc-service
    image: aproc-service:latest
    container_name: 'aproc-service'
    depends_on:
      elasticsearch:
        condition: service_healthy
      redis:
          condition: service_healthy
      rabbitmq:
          condition: service_healthy
    environment:
      - ARLAS_URL_SEARCH=$ARLAS_URL_SEARCH
      - APROC_HOST=0.0.0.0
      - APROC_PORT=8001
      - APROC_CORS_ORIGINS=${APROC_CORS_ORIGINS:-*}
      - APROC_CORS_METHODS=${APROC_CORS_METHODS:-*}
      - APROC_CORS_HEADERS=${APROC_CORS_HEADERS:-*}
      - APROC_CONFIGURATION_FILE=/app/conf/aproc.yaml
      - CELERY_BROKER_URL=pyamqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - AIRS_ENDPOINT=http://airs-server:8000/arlas/airs
      - AIRS_INDEX_COLLECTION_PREFIX=${AIRS_INDEX_COLLECTION_PREFIX:-airs}
      - ARLAS_SMTP_ACTIVATED=${ARLAS_SMTP_ACTIVATED}
      - ARLAS_SMTP_HOST=${ARLAS_SMTP_HOST}
      - ARLAS_SMTP_PORT=${ARLAS_SMTP_PORT}
      - ARLAS_SMTP_USERNAME=${ARLAS_SMTP_USERNAME}
      - ARLAS_SMTP_PASSWORD=${ARLAS_SMTP_PASSWORD}
      - ARLAS_SMTP_FROM=${ARLAS_SMTP_FROM}
      - APROC_DOWNLOAD_ADMIN_EMAILS=${APROC_DOWNLOAD_ADMIN_EMAILS}
      - APROC_DOWNLOAD_OUTBOX_DIR=${APROC_DOWNLOAD_OUTBOX_DIR}
      - APROC_DOWNLOAD_CONTENT_USER=${APROC_DOWNLOAD_CONTENT_USER}
      - APROC_DOWNLOAD_SUBJECT_USER=${APROC_DOWNLOAD_SUBJECT_USER}
      - APROC_DOWNLOAD_CONTENT_ERROR=${APROC_DOWNLOAD_CONTENT_ERROR}
      - APROC_DOWNLOAD_SUBJECT_ERROR=${APROC_DOWNLOAD_SUBJECT_ERROR}
      - APROC_DOWNLOAD_CONTENT_ADMIN=${APROC_DOWNLOAD_CONTENT_ADMIN}
      - APROC_DOWNLOAD_SUBJECT_ADMIN=${APROC_DOWNLOAD_SUBJECT_ADMIN}
      - APROC_EMAIL_PATH_PREFIX_ADD=${APROC_EMAIL_PATH_PREFIX_ADD}
      - APROC_PATH_TO_WINDOWS=${APROC_PATH_TO_WINDOWS}
      - APROC_DOWNLOAD_REQUEST_SUBJECT_USER=${APROC_DOWNLOAD_REQUEST_SUBJECT_USER}
      - APROC_DOWNLOAD_REQUEST_CONTENT_USER=${APROC_DOWNLOAD_REQUEST_CONTENT_USER}
      - APROC_DOWNLOAD_REQUEST_SUBJECT_ADMIN=${APROC_DOWNLOAD_REQUEST_SUBJECT_ADMIN}
      - APROC_DOWNLOAD_REQUEST_CONTENT_ADMIN=${APROC_DOWNLOAD_REQUEST_CONTENT_ADMIN}
      - APROC_LOGGER_LEVEL=${APROC_LOGGER_LEVEL:-INFO}
      - APROC_INDEX_ENDPOINT_URL=${APROC_INDEX_ENDPOINT_URL}
      - APROC_INDEX_NAME=${APROC_INDEX_NAME}
      - APROC_INDEX_LOGIN=${APROC_INDEX_LOGIN:-None}
      - APROC_INDEX_PWD=${APROC_INDEX_PWD:-None}
      - APROC_RESOURCE_ID_HASH_STARTS_AT=${APROC_RESOURCE_ID_HASH_STARTS_AT}
      - APROC_INPUT_STORAGE_TYPE=${APROC_INPUT_STORAGE_TYPE}
      - APROC_INPUT_STORAGE_BUCKET=${APROC_INPUT_STORAGE_BUCKET}
      - APROC_INPUT_STORAGE_API_KEY_PROJECT=${APROC_INPUT_STORAGE_API_KEY_PROJECT}
      - APROC_INPUT_STORAGE_API_KEY_PRIVATE_KEY_ID=${APROC_INPUT_STORAGE_API_KEY_PRIVATE_KEY_ID}
      - APROC_INPUT_STORAGE_API_KEY_PRIVATE_KEY=${APROC_INPUT_STORAGE_API_KEY_PRIVATE_KEY}
      - APROC_INPUT_STORAGE_HEADERS=${APROC_INPUT_STORAGE_HEADERS}
      - APROC_INPUT_STORAGE_DOMAIN=${APROC_INPUT_STORAGE_DOMAIN}
      - APROC_INPUT_STORAGE_FORCE_DOWNLOAD=${APROC_INPUT_STORAGE_FORCE_DOWNLOAD}

    volumes:
      - ./test/inputs:/inputs:ro
    ports:
      - "8001:8001"
    healthcheck:
      test: "curl -f http://localhost:8001/arlas/aproc/healthcheck"
      interval: 5s
      timeout: 3s
      retries: 30

  fam-service:
    networks:
      - aias
    build:
      context: '.'
      dockerfile: Dockerfile-fam
    image: fam:latest
    container_name: 'fam-service'
    environment:
      - INGESTED_FOLDER=/inputs
      - FAM_PREFIX=${FAM_PREFIX:-/arlas/fam}
      - FAM_CORS_ORIGINS=${FAM_CORS_ORIGINS:-*}
      - FAM_CORS_METHODS=${FAM_CORS_METHODS:-*}
      - FAM_CORS_HEADERS=${FAM_CORS_HEADERS:-*}
      - APROC_CONFIGURATION_FILE=/app/conf/aproc.yaml
    volumes:
      - ./test/inputs:/inputs:ro
    ports:
      - "8005:8005"

  fam-bucket-service:
    networks:
      - aias
    build:
      context: '.'
      dockerfile: Dockerfile-fam
    image: fam:latest
    container_name: 'fam-bucket-service'
    environment:
      - INGESTED_FOLDER=gs://gisaia-public/
      - FAM_PREFIX=${FAM_PREFIX:-/arlas/fam}
      - FAM_CORS_ORIGINS=${FAM_CORS_ORIGINS:-*}
      - FAM_CORS_METHODS=${FAM_CORS_METHODS:-*}
      - FAM_CORS_HEADERS=${FAM_CORS_HEADERS:-*}
      - APROC_CONFIGURATION_FILE=/app/conf/aproc.yaml
    volumes:
      - ./test/inputs:/inputs:ro
    ports:
      - "8006:8005"
