FROM python:3.10.13-alpine3.19
ARG version="0.0"
ENV AIAS_VERSION=${version}

LABEL io.arlas.aproc-service.version=${version}
LABEL vendor="Gisaïa"
LABEL description="This container serves ARLAS APROC Service"

RUN apk update && apk add --upgrade libexpat

RUN apk --no-cache add curl

COPY ./aproc/requirements.txt /app/requirements.txt
COPY ./extensions/requirements.storage.txt /app/requirements.storage.txt

WORKDIR /app

RUN pip install -r requirements.txt
RUN pip install -r requirements.storage.txt

ENV APP_HOME=/app

COPY ./aproc $APP_HOME/aproc
COPY ./extensions $APP_HOME/extensions
COPY ./airs/core/ $APP_HOME/airs/core/
COPY ./aias_common $APP_HOME/aias_common
COPY ./conf $APP_HOME/conf
COPY ./scripts/aproc/start.sh $APP_HOME/
COPY ./conf $APP_HOME/conf

ENV APROC_CONFIGURATION_FILE=$APP_HOME/conf/aproc.yaml
ENV PYTHONPATH=PYTHONPATH=$PYTHONPATH:$APP_HOME

EXPOSE 8001
ENTRYPOINT ["./start.sh"]