FROM python:3.10.17-alpine3.21

ARG version="latest"
ENV AIAS_VERSION=${version}

LABEL io.arlas.agate.version=${version}
LABEL vendor="Gisaïa"
LABEL description="This container serves ARLAS AGATE"

RUN apk update && apk add --upgrade libexpat

COPY ./agate/requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

COPY ./agate /app/agate
COPY ./aias_common /app/aias_common
COPY ./conf/agate.yaml /app/conf/
COPY ./scripts/agate/start.sh /app/

EXPOSE 8004
ENTRYPOINT ["./start.sh"]
