FROM python:3.10.13-alpine3.19

RUN apk --no-cache add curl

COPY ./aproc/requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

COPY ./aproc /app/aproc
COPY ./extensions /app/extensions
# TODO : move to python package with pip3 install
COPY ./airs/core/models /app/airs/core/models
COPY ./airs/core/models/__init__.py /app/airs/core/models/__init__.py
COPY ./airs/__init__.py /app/airs/__init__.py
COPY ./common /app/common
COPY ./conf /app/conf
COPY ./scripts/aproc/start.sh /app/
COPY ./conf /app/conf

ENV APROC_CONFIGURATION_FILE=/app/conf/aproc.yaml
ENV PYTHONPATH=PYTHONPATH=$PYTHONPATH:$APP_HOME

EXPOSE 8001
ENTRYPOINT ["./start.sh"]