FROM python:3.10.13-alpine3.19
RUN apk update && apk add --upgrade libexpat
RUN apk --no-cache add curl

COPY test/requirements.txt /app/requirements.txt
COPY ./extensions/requirements.storage.txt /app/requirements.storage.txt

COPY ./conf/aproc.yaml /app/conf/aproc.yaml
ENV APROC_CONFIGURATION_FILE /app/conf/aproc.yaml

WORKDIR /app

RUN pip install -r requirements.txt
RUN pip install -r requirements.storage.txt
