FROM python:3.10.13-alpine3.19
RUN apk update && apk add --upgrade libexpat

RUN apk --no-cache add curl

COPY ./aproc/requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

COPY ./aproc /app/aproc
COPY ./extensions /app/extensions
# TODO : move to python package with pip3 install
COPY ./airs/core/models /app/airs/core/models
COPY ./airs/core/models/__init__.py /app/airs/core/models/__init__.py
COPY ./airs/__init__.py /app/airs/__init__.py
COPY ./common /app/common
COPY ./conf /app/conf
COPY ./test/ingest.py /app/ingest.py
COPY ./test/utils.py /app/utils.py

ENV APROC_CONFIGURATION_FILE=/app/conf/aproc.yaml
ENV DRIVERS_CONFIGURATION_FILE=/app/conf/drivers.yaml

ENV PYTHONPATH=PYTHONPATH=$PYTHONPATH:$APP_HOME

CMD ["python3", "ingest.py"]
