FROM python:3.10.17-alpine3.21
RUN pip3 install --upgrade pip setuptools

ARG version="0.0"
ENV AIAS_VERSION=${version}

LABEL io.arlas.geodes-stac.version=${version}
LABEL vendor="Gisaïa"
LABEL description="This container serves ARLAS GEODES STAC Sync"

RUN apk update && apk add --upgrade libexpat
RUN apk --no-cache add curl
COPY requirements-stac.txt /app/requirements.txt

WORKDIR /app

RUN pip3 install -r requirements.txt

COPY stac /app/stac
COPY ./airs /app/airs
COPY ./aias_common /app/aias_common

ENV PYTHONPATH=/app

ENTRYPOINT ["python3.10", "-m", "stac.geodes_sync"]
