FROM python:3.10.18-alpine3.22
RUN pip3 install --no-cache-dir --upgrade pip setuptools

RUN apk update && apk add --upgrade libexpat
RUN apk --no-cache add curl gcc python3-dev musl-dev linux-headers

COPY ./test/requirements.tests.txt /app/
COPY ./python/aias_common/requirements.aias_common.txt /app/

COPY ./conf/aproc.yaml /app/conf/aproc.yaml
ENV APROC_CONFIGURATION_FILE=/app/conf/aproc.yaml
ENV PYTHONPATH=/app/python/

WORKDIR /app

RUN pip install -r requirements.tests.txt
RUN pip install -r requirements.aias_common.txt
