FROM python:3.14-alpine3.24
RUN pip3 install --no-cache-dir --upgrade pip setuptools

RUN apk update && apk add --upgrade libexpat
RUN apk --no-cache add curl gcc python3-dev musl-dev linux-headers

# 1. Installation des dépendances système nécessaires à l'exécution et à la compilation
RUN apk add --no-cache \
    gdal \
    gdal-dev \
    # Dépendances requises pour compiler l'extension C++ (supprimées après coup pour alléger l'image)
    && apk add --no-cache --virtual .build-deps \
    gcc \
    g++ \
    musl-dev \
    python3-dev \
    && pip install --no-cache-dir --upgrade pip setuptools wheel

# 2. Installation de GDAL via pip (aligné précisément sur la version système)
RUN pip install gdal==3.13.0

# 3. Nettoyage des paquets de compilation devenus inutiles
RUN apk del .build-deps


COPY ./test/requirements.tests.txt /app/
COPY ./python/aias_common/requirements.aias_common.txt /app/

COPY ./conf/aproc.yaml /app/conf/aproc.yaml
ENV APROC_CONFIGURATION_FILE=/app/conf/aproc.yaml
ENV PYTHONPATH=/app/python/

WORKDIR /app

RUN pip install -r requirements.tests.txt -r requirements.aias_common.txt
