FROM ghcr.io/osgeo/gdal:ubuntu-full-3.10.3
ARG version="0.0"
ENV AIAS_VERSION=${version}

LABEL io.arlas.aproc-proc.version=${version}
LABEL vendor="Gisaïa"
LABEL description="This container serves ARLAS APROC Processing"

WORKDIR /usr/src

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update --no-install-recommends \
    && apt-get install -y python3.12-dev python3.12-venv \
    && apt-get install -y g++ make  \
    && apt-get install -y libtiff-dev imagemagick  \
    && apt-get install -y libhdf5-dev libhdf5-serial-dev netcdf-bin libnetcdf-dev \
    && apt-get upgrade -y \
    && apt-get clean && apt-get remove -y --auto-remove curl

USER 1000
WORKDIR /app

RUN python -m venv --system-site-packages aproc

COPY ./python/requirements.aias.services.txt /app/

COPY ./python/aias_common/requirements.aias_common.txt /app/

COPY ./python/aproc/requirements.aproc.txt /app/
RUN aproc/bin/pip install --no-cache-dir -r /app/requirements.aproc.txt 

COPY ./python/extensions/requirements.aproc.ext.txt /app/
RUN aproc/bin/pip install --no-cache-dir -r /app/requirements.aproc.ext.txt 


COPY ./python/aproc /app/aproc
COPY ./python/extensions /app/extensions
COPY ./python/aias_common /app/aias_common
COPY ./conf /app/conf
COPY ./python/assets /app/assets
COPY ./python/airs/core /app/airs/core
COPY ./docker/materials/scripts/aproc-proc/start.sh /app/
COPY ./docker/materials/scripts/aproc-proc/ping.sh /app/

ENV APROC_CONFIGURATION_FILE=/app/conf/aproc.yaml
ENV ARLASEO_MAPPING_URL=/app/conf/mapping.json
ENV DOWNLOAD_MAPPING_URL=/app/conf/downloads_mapping.json
ENV PYTHONPATH=/app

ENTRYPOINT ["./start.sh"]
