FROM python:3.14-alpine3.24
RUN pip3 install --no-cache-dir --upgrade pip setuptools

ARG version="latest"
ENV AIAS_VERSION=${version}

LABEL io.arlas.agate.version=${version}
LABEL vendor="Gisaïa"
LABEL description="This container serves ARLAS AGATE"

RUN apk update && apk add  --no-cache --upgrade libexpat curl gcc python3-dev musl-dev linux-headers libcrypto3 libssl3

RUN addgroup -g 1000 arlasgroup && \
    adduser -D -u 1000 -G arlasgroup arlasuser
USER 1000
WORKDIR /app

COPY ./python/requirements.aias.services.txt /app/

COPY ./python/agate/requirements.agate.txt /app/
RUN pip install --no-cache-dir -r requirements.agate.txt

COPY ./python/agate /app/agate
COPY ./python/aias_common /app/aias_common
COPY ./conf/agate.yaml /app/conf/
COPY ./docker/materials/scripts/agate/start.sh /app/

EXPOSE 8004
ENTRYPOINT ["./start.sh"]
