FROM python:3.12-alpine3.23
RUN pip3 install --no-cache-dir --upgrade pip setuptools

ARG version="0.0"
ENV AIAS_VERSION=${version}

LABEL io.arlas.airs.version=${version}
LABEL vendor="Gisaïa"
LABEL description="This container serves ARLAS AIRS"

RUN apk update && apk add  --no-cache --upgrade libexpat curl gcc python3-dev musl-dev linux-headers libcrypto3 libssl3

RUN addgroup -g 1000 arlasgroup && \
    adduser -D -u 1000 -G arlasgroup arlasuser
USER 1000
WORKDIR /app

COPY ./python/requirements.aias.services.txt /app/

COPY ./python/airs/requirements.airs.txt /app/
RUN pip install --no-cache-dir -r requirements.airs.txt

COPY ./python/airs /app/airs
COPY ./python/aias_common /app/aias_common
COPY ./conf /app/conf
COPY ./docker/materials/scripts/airs/start.sh /app/

EXPOSE 8000
ENTRYPOINT ["./start.sh"]