FROM python:3.12-alpine3.22
ARG version="0.0"
ENV AIAS_VERSION=${version}

LABEL io.arlas.aproc-service.version=${version}
LABEL vendor="Gisaïa"
LABEL description="This container serves ARLAS APROC Service"

RUN apk update \
    && apk add --no-cache python3 py3-pip \
    && apk --no-cache add curl gcc python3-dev musl-dev linux-headers

RUN addgroup -g 1000 arlasgroup && \
    adduser -D -u 1000 -G arlasgroup arlasuser

USER 1000
WORKDIR /app

RUN python -m venv --system-site-packages aproc

COPY ./python/requirements.aias.services.txt /app/

COPY ./python/aias_common/requirements.aias_common.txt /app/

COPY ./python/aproc/requirements.aproc.txt /app/
RUN aproc/bin/pip install --no-cache-dir -r requirements.aproc.txt


COPY ./python/aproc /app/aproc
COPY ./python/extensions /app/extensions
COPY ./python/airs/core/ /app/airs/core/
COPY ./python/aias_common /app/aias_common
COPY ./conf /app/conf
COPY ./docker/materials/scripts/aproc/start.sh /app/
COPY ./conf /app/conf

ENV APROC_CONFIGURATION_FILE=/app/conf/aproc.yaml
ENV PYTHONPATH=/app/

EXPOSE 8001
ENTRYPOINT ["./start.sh"]