FROM python:3.10.17-alpine3.21
RUN pip3 install --upgrade pip setuptools

ARG version="0.0"
ENV AIAS_VERSION=${version}

LABEL io.arlas.geodes-stac.version=${version}
LABEL vendor="Gisaïa"
LABEL description="This container serves ARLAS GEODES STAC Sync"

RUN apk update && apk --no-cache add curl

RUN addgroup -g 1000 arlasgroup && \
    adduser -D -u 1000 -G arlasgroup arlasuser
USER 1000
WORKDIR /app
COPY --chown=arlasuser:arlasgroup python/requirements-stac.txt /app/requirements.txt

RUN pip3 install --no-cache-dir -r requirements.txt

COPY --chown=arlasuser:arlasgroup ./python/stac /app/stac
COPY --chown=arlasuser:arlasgroup ./python/airs /app/airs
COPY --chown=arlasuser:arlasgroup ./python/aias_common /app/aias_common

ENV PYTHONPATH=/app
ENTRYPOINT ["python3.10", "-m", "stac.geodes_sync"]
