FROM python:3.10.18-alpine3.22
RUN pip3 install --no-cache-dir --upgrade pip setuptools

ARG version="latest"
ENV AIAS_VERSION=${version}

LABEL io.arlas.agate.version=${version}
LABEL vendor="Gisaïa"
LABEL description="This container serves ARLAS AGATE"

RUN addgroup -g 1000 arlasgroup && \
    adduser -D -u 1000 -G arlasgroup arlasuser
USER 1000
WORKDIR /app

COPY --chown=arlasuser:arlasgroup ./python/agate/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY --chown=arlasuser:arlasgroup ./python/agate /app/agate
COPY --chown=arlasuser:arlasgroup ./python/aias_common /app/aias_common
COPY --chown=arlasuser:arlasgroup ./conf/agate.yaml /app/conf/
COPY --chown=arlasuser:arlasgroup ./docker/materials/scripts/agate/start.sh /app/

EXPOSE 8004
ENTRYPOINT ["./start.sh"]
