ARG AIAS_DOCKER_BASE_IMAGE="python:3.14-alpine3.24"
FROM $AIAS_DOCKER_BASE_IMAGE

ARG version="0.0"
ENV AIAS_VERSION=${version}

LABEL io.arlas.aproc-service.version=${version}
LABEL vendor="Gisaïa"
LABEL description="This container serves ARLAS APROC Service"

RUN apk update \
    && apk add --no-cache python3 py3-pip \
    && apk add --no-cache --upgrade libexpat curl gcc python3-dev musl-dev linux-headers libcrypto3 libssl3

#Clean SBOM pip to fix false positive CVE CVE-2025-47273 about setuptools
#pip show setuptools → “not found” (because it is not installed via pip).
#apk info py3-setuptools → 82.0.1 (system version).
#SBOM bom.cdx.json → setuptools@70.3.0 (version documented at the time pip was built but not really instaled).
RUN rm -f /usr/local/lib/python3.14/site-packages/pip/_vendor/bom.cdx.json

RUN addgroup -g 1000 arlasgroup && \
    adduser -D -u 1000 -G arlasgroup arlasuser

USER 1000
WORKDIR /app

RUN python -m venv --system-site-packages aproc

COPY ./python/requirements.aias.services.txt /app/

COPY ./python/aias_common/requirements.aias_common.txt /app/

COPY ./python/aproc/requirements.aproc.txt /app/
RUN aproc/bin/pip install --no-cache-dir -r requirements.aproc.txt
RUN rm -f /app/aproc/lib/python3.14/site-packages/pip/_vendor/bom.cdx.json


COPY ./python/aproc /app/aproc
COPY ./python/extensions /app/extensions
COPY ./python/airs/core/ /app/airs/core/
COPY ./python/aias_common /app/aias_common
COPY ./conf /app/conf
COPY ./docker/materials/scripts/aproc/start.sh /app/
COPY ./conf /app/conf

ENV APROC_CONFIGURATION_FILE=/app/conf/aproc.yaml
ENV PYTHONPATH=/app/

EXPOSE 8001
ENTRYPOINT ["./start.sh"]