FROM python:3.14-alpine3.24

ARG version="0.0"
ENV AIAS_VERSION=${version}

LABEL io.arlas.geodes-stac.version=${version}
LABEL vendor="Gisaïa"
LABEL description="This container serves ARLAS GEODES STAC Sync"

RUN apk update && apk --no-cache add curl

#Clean SBOM pip to fix false positive CVE CVE-2025-47273 about setuptools
#pip show setuptools → “not found” (because it is not installed via pip).
#apk info py3-setuptools → 82.0.1 (system version).
#SBOM bom.cdx.json → setuptools@70.3.0 (version documented at the time pip was built but not really instaled).
RUN rm -f /usr/local/lib/python3.14/site-packages/pip/_vendor/bom.cdx.json

RUN addgroup -g 1000 arlasgroup && \
    adduser -D -u 1000 -G arlasgroup arlasuser
USER 1000
WORKDIR /app

COPY ./python/requirements.aias.services.txt /app/

COPY ./python/requirements.stac.txt /app/
RUN pip install --no-cache-dir -r requirements.stac.txt

COPY ./python/stac /app/stac
COPY ./python/airs /app/airs
COPY ./python/aias_common /app/aias_common

ENV PYTHONPATH=/app
ENTRYPOINT ["python3.10", "-m", "stac.geodes_sync"]
