FROM python:3.12-alpine3.22
RUN pip3 install --no-cache-dir --upgrade pip setuptools

ARG version="0.0"
ENV AIAS_VERSION=${version}

LABEL io.arlas.geodes-stac.version=${version}
LABEL vendor="Gisaïa"
LABEL description="This container serves ARLAS GEODES STAC Sync"

RUN apk update && apk --no-cache add curl

RUN addgroup -g 1000 arlasgroup && \
    adduser -D -u 1000 -G arlasgroup arlasuser
USER 1000
WORKDIR /app

COPY ./python/requirements.aias.services.txt /app/

COPY ./python/requirements.stac.txt /app/
RUN pip install --no-cache-dir -r requirements.stac.txt

COPY ./python/stac /app/stac
COPY ./python/airs /app/airs
COPY ./python/aias_common /app/aias_common

ENV PYTHONPATH=/app
ENTRYPOINT ["python3.10", "-m", "stac.geodes_sync"]
