FROM python:3.14-alpine3.24
RUN pip3 install --no-cache-dir --upgrade  pip setuptools

ARG version="0.0"
ENV AIAS_VERSION=${version}

LABEL io.arlas.fam.version=${version}
LABEL vendor="Gisaïa"
LABEL description="This container serves ARLAS APROC FAM"

RUN apk update && apk add  --no-cache --upgrade libexpat curl gcc python3-dev musl-dev linux-headers libcrypto3 libssl3

RUN addgroup -g 1000 arlasgroup && \
    adduser -D -u 1000 -G arlasgroup arlasuser
USER 1000
WORKDIR /app

COPY ./python/requirements.aias.services.txt /app/

COPY ./python/aias_common/requirements.aias_common.txt /app/

COPY ./python/fam/requirements.fam.txt /app/
RUN pip install --no-cache-dir -r requirements.fam.txt

COPY ./python/aproc /app/aproc
COPY ./python/extensions /app/extensions
COPY ./python/fam /app/fam
COPY ./python/airs/core/models /app/airs/core/models
COPY ./python/airs/core/models/__init__.py /app/airs/core/models/__init__.py
COPY ./python/aias_common /app/aias_common
COPY ./conf/fam.yaml /app/conf/
COPY ./conf/drivers.yaml /app/conf/
COPY ./conf/aproc.yaml /app/conf/

COPY ./docker/materials/scripts/fam/start.sh /app/

EXPOSE 8005

ENV APROC_CONFIGURATION_FILE=/app/conf/aproc.yaml
ENV PYTHONPATH=PYTHONPATH=$PYTHONPATH:/app
ENTRYPOINT ["./start.sh"]
