FROM ghcr.io/osgeo/gdal:ubuntu-small-3.10.3
ARG version="0.0"
ENV AIAS_VERSION=${version}

LABEL io.arlas.aproc-proc.version=${version}
LABEL vendor="Gisaïa"
LABEL description="This container serves ARLAS APROC Processing"

WORKDIR /usr/src

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update --no-install-recommends \
    && apt-get install -y g++ make libtiff-dev imagemagick \
    && apt-get install -y python3.12-venv \
    && apt-get clean \
    && apt-get remove -y --auto-remove curl

USER 1000
WORKDIR /app

COPY ./python/aproc/requirements.txt \
    ./python/extensions/requirements.ext.txt \
    ./python/extensions/requirements.storage.txt \
    /app/

RUN python -m venv --system-site-packages aproc
RUN aproc/bin/pip install --no-cache-dir \
    -r /app/requirements.txt \
    -r /app/requirements.ext.txt \
    -r /app/requirements.storage.txt

COPY ./python/aproc /app/aproc
COPY ./python/extensions /app/extensions
COPY ./python/aias_common /app/aias_common
COPY ./conf /app/conf
COPY ./python/assets /app/assets
COPY ./python/airs/core /app/airs/core
COPY ./docker/materials/scripts/aproc-proc/start.sh /app/

ENV APROC_CONFIGURATION_FILE=/app/conf/aproc.yaml
ENV ARLASEO_MAPPING_URL=/app/conf/mapping.json
ENV DOWNLOAD_MAPPING_URL=/app/conf/downloads_mapping.json
ENV PYTHONPATH=/app

ENTRYPOINT ["./start.sh"]