authentication:
  use_authent: true
  auth_mode: 'iam'
  force_connect: true
  threshold: 60000
  url: https://localhost/arlas_iam_server
  sign_up_enabled: false
file_manager:
  url: https://localhost/fam
  default_path: ''
  collection: 'catalogue'
  archives_page_size: 20
  files_page_size: 50
jobs:
  url: https://localhost/aproc
  collection: 'catalogue'
  catalog: 'catalogue'
status:
  url: https://localhost/airs
  collection: 'catalogue'