version: "3"
networks:
  aias:
services:
  createbuckets:
    image: ${SEAWEEDFS_VERSION}
    depends_on:
      seaweedfs:
        condition: service_healthy
    environment:
      - BUCKET_NAME=${BUCKET_NAME:-airstest}
    networks:
      - aias
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "create bucket $$BUCKET_NAME"
        echo "s3.bucket.create -name $$BUCKET_NAME" | weed shell -master=seaweedfs:9333 -filer=seaweedfs:8888
        if [ "$$BUCKET_NAME" = "archives" ]; then
          weed filer.copy /inputs http://seaweedfs:8888/buckets/archives/       
        fi
        exit 0
    volumes:
      - ${PWD}/test/inputs:/inputs:ro