name: Linting AIAS

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install flake8
        run: pip --disable-pip-version-check install flake8
      - name: Linting with flake8
        run: flake8 agate airs aproc common extensions fam test --max-line-length 1000 --extend-exclude=__init__.py
  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install isort
        run: pip --disable-pip-version-check install isort
      - name: Running isort
        run: isort agate airs aproc common extensions fam test --check-only
