name: Test AIAS
on:
  workflow_dispatch:
    inputs:
      run_all:
        description: 'Run All?'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
jobs:
  test:
    if: inputs.run_all == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Workflow is running!"



