name: Test AIAS

on: push

jobs:
  aias-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install test/requirements
      run: |
        pip install -r test/requirements.txt
    - name: Run  tests
      run: test/tests.sh
