name: Test AIAS

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - develop
      - master

  workflow_dispatch:
    inputs:
      run_all:
        description: 'Run All?'
        required: true
        default: false
        type: boolean

      run_hadolint:
        description: 'Run Hadolint?'
        required: true
        default: false
        type: boolean

      run_aias_am:
        description: 'Run AIAS AM tests?'
        required: true
        default: false
        type: boolean

      run_aias_download:
        description: 'Run AIAS Downloads tests?'
        required: true
        default: false
        type: boolean

      run_aias_airs_agate_fam:
        description: 'Run AIAS AIRS+agate+fam tests?'
        required: true
        default: false
        type: boolean
      run_aias_dc3:
        description: 'Run AIAS DC3 tests?'
        required: true
        default: false
        type: boolean
      run_aias_ingest:
        description: 'Run AIAS Ingest tests?'
        required: true
        default: false
        type: boolean
      run_geodes_stac:
        description: 'Run Geodes STAC tests?'
        required: true
        default: false
        type: boolean


jobs:
 
  aias-tests-am:
    if: (github.event_name == 'pull_request' && github.actor != 'dependabot[bot]') || (github.event_name == 'workflow_dispatch' && (inputs.run_aias_am || inputs.run_all))
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install test/requirements
      run: |
        pip install -r test/requirements.tests.txt
    - name: Start stack
      run: test/start_stack.sh
    - name: Run am tests
      run: test/tests_am.sh


  aias-tests-downloads:
    if: (github.event_name == 'pull_request' && github.actor != 'dependabot[bot]') || (github.event_name == 'workflow_dispatch' && (inputs.run_aias_download || inputs.run_all))
    runs-on: runner-8core-32gb
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install test/requirements
      run: |
        pip install -r test/requirements.tests.txt
    - name: Start stack
      run: test/start_stack.sh
    - name: Run downloads tests
      run: test/tests_downloads.sh
    - name: Logs dockers aproc-service
      run: test/logs.sh aproc-service 
      if: always()
    - name: Logs dockers compose-aproc-processes-fast-1
      run: test/logs.sh compose-aproc-processes-fast-1 
      if: always()
    - name: Logs dockers compose-aproc-processes-fast-medium-large-1
      run: test/logs.sh compose-aproc-processes-fast-medium-large-1 
      if: always()
      
  aias-tests-airs-agate-fam:
    if: (github.event_name == 'pull_request' && github.actor != 'dependabot[bot]') || (github.event_name == 'workflow_dispatch' && (inputs.run_aias_airs_agate_fam || inputs.run_all))
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install test/requirements
      run: |
        pip install -r test/requirements.tests.txt
    - name: Start stack
      run: test/start_stack.sh
    - name: Logs dockers aproc-service
      run: test/logs.sh arlas-server
      if: always()
    - name: Run airs, agate and fam tests
      run: test/tests_airs_agate_fam.sh
    - name: Logs dockers aproc-service
      run: test/logs.sh aproc-service 
      if: always()
    - name: Logs dockers compose-aproc-processes-fast-1
      run: test/logs.sh compose-aproc-processes-fast-1 
      if: always()
    - name: Logs dockers compose-aproc-processes-fast-medium-large-1
      run: test/logs.sh compose-aproc-processes-fast-medium-large-1 
      if: always()


  aias-tests-dc3:
    if: (github.event_name == 'pull_request' && github.actor != 'dependabot[bot]') || (github.event_name == 'workflow_dispatch' && (inputs.run_aias_dc3 || inputs.run_all))
    runs-on: runner-8core-32gb
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install test/requirements
      run: |
        pip install -r test/requirements.tests.txt
    - name: Start stack
      run: test/start_stack.sh
    - name: Run dc3 tests
      run: test/tests_dc3.sh
    - name: Logs dockers aproc-service
      run: test/logs.sh aproc-service 
      if: always()
    - name: Logs dockers compose-aproc-processes-fast-1
      run: test/logs.sh compose-aproc-processes-fast-1 
      if: always()
    - name: Logs dockers compose-aproc-processes-fast-medium-large-1
      run: test/logs.sh compose-aproc-processes-fast-medium-large-1 
      if: always()
  

  aias-tests-ingest-fs:
    if: (github.event_name == 'pull_request' && github.actor != 'dependabot[bot]') || (github.event_name == 'workflow_dispatch' && (inputs.run_aias_ingest_fs || inputs.run_all))
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install test/requirements
      run: |
        pip install -r test/requirements.tests.txt
    - name: Start stack fs
      run: test/start_stack.sh
    - name: Run ingest tests on file system
      run: test/tests_ingest_fs.sh
    - name: Logs dockers aproc-service
      run: test/logs.sh aproc-service 
      if: always()
    - name: Logs dockers compose-aproc-processes-fast-1
      run: test/logs.sh compose-aproc-processes-fast-1 
      if: always()
    - name: Logs dockers compose-aproc-processes-fast-medium-large-1
      run: test/logs.sh compose-aproc-processes-fast-medium-large-1 
      if: always()
  

  aias-tests-ingest-gs:
    if: (github.event_name == 'pull_request' && github.actor != 'dependabot[bot]') || (github.event_name == 'workflow_dispatch' && (inputs.run_aias_ingest_gs || inputs.run_all))
    runs-on: runner-8core-32gb
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install test/requirements
      run: |
        pip install -r test/requirements.tests.txt
    - name: Start stack gs
      run: test/start_stack.sh gs
    - name: Run ingest tests on google storage
      run: test/tests_ingest_gs.sh
    - name: Logs dockers aproc-service
      run: test/logs.sh aproc-service 
      if: always()
    - name: Logs dockers compose-aproc-processes-fast-1
      run: test/logs.sh compose-aproc-processes-fast-1 
      if: always()
    - name: Logs dockers compose-aproc-processes-fast-medium-large-1
      run: test/logs.sh compose-aproc-processes-fast-medium-large-1 
      if: always()
  
  aias-tests-ingest-minio:
    if: (github.event_name == 'pull_request' && github.actor != 'dependabot[bot]') || (github.event_name == 'workflow_dispatch' && (inputs.run_aias_ingest_minio || inputs.run_all))
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install test/requirements
      run: |
        pip install -r test/requirements.tests.txt
    - name: Start stack minio
      run: test/start_stack.sh minio
    - name: Run ingest tests on minio
      run: test/tests_ingest_minio.sh
    - name: Logs dockers aproc-service
      run: test/logs.sh aproc-service 
      if: always()
    - name: Logs dockers compose-aproc-processes-fast-1
      run: test/logs.sh compose-aproc-processes-fast-1 
      if: always()
    - name: Logs dockers compose-aproc-processes-fast-medium-large-1
      run: test/logs.sh compose-aproc-processes-fast-medium-large-1 
      if: always()
  

  geodes-stac-test:
    if: (github.event_name == 'pull_request' && github.actor != 'dependabot[bot]') || (github.event_name == 'workflow_dispatch' && (inputs.run_geodes_stac || inputs.run_all))
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install python/requirements.stac.txt
      run: |
        pip install -r python/requirements.stac.txt
    - name: Run  tests
      run: test/test_geodes_stac.sh
  