name: Test AIAS

on: push

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "Dockerfile*"


  dockle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker images
        run: ./release/build_docker_images.sh tests

      - name: Install Dockle
        run: |
          VERSION=$(curl --silent "https://api.github.com/repos/goodwithtech/dockle/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
          curl -L -o dockle https://github.com/goodwithtech/dockle/releases/download/v${VERSION}/dockle_${VERSION}_Linux-64bit
          chmod +x dockle

      - name: Run Dockle
        run: ./release/quality.sh tests

  aias-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install test/requirements
      run: |
        pip install -r test/requirements.txt
    - name: Run  tests
      run: test/tests.sh

  geodes-stac-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install requirements-stac.txt
      run: |
        pip install -r requirements-stac.txt
    - name: Run  tests
      run: test/test_geodes_stac.sh

  