name: Test AIAS

on: push

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          failure-threshold: "error"
          dockerfile: "docker/Dockerfile-airs"
 
  aias-tests-g1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install test/requirements
      run: |
        pip install -r test/requirements.txt
    - name: Run  tests
      run: test/tests_g1.sh


  aias-tests-g2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install test/requirements
      run: |
        pip install -r test/requirements.txt
    - name: Run  tests
      run: test/tests_g2.sh


  geodes-stac-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install python/requirements-stac.txt
      run: |
        pip install -r python/requirements-stac.txt
    - name: Run  tests
      run: test/test_geodes_stac.sh
  