name: Test AIAS

on: push

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          failure-threshold: "error"
          dockerfile: "Dockerfile-airs"

  dockle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Docker images
        run: ./release/build_docker_images.sh tests
      - name: Run Dockle agate
        uses: goodwithtech/dockle-action@main
        with:
          image: 'gisaia/agate:tests'
          format: 'list'
          exit-code: '1'
          exit-level: 'warn'

            #            ignore: 'CIS-DI-0001,DKL-DI-0006'
        
      # - name: Run Dockle agate
      #   run: ./dockle --exit-level WARN -af settings.py gisaia/agate:tests
      # - name: Run Dockle agate
      #   run: ./dockle -af settings.py gisaia/airs:tests
      # - name: Run Dockle agate
      #   run: ./dockle -af settings.py gisaia/fam:tests      
      # - name: Run Dockle agate
      #   run: ./dockle -af settings.py -i CIS-DI-0009 -i DKL-DI-0005 gisaia/aproc-proc:tests
      # - name: Run Dockle agate
      #   run: ./dockle -af settings.py gisaia/aproc-service:tests
      # - name: Run Dockle agate
      #   run: ./dockle -af settings.py --accept-key KEY_SHA512 gisaia/arlas-fam-wui:tests
      # - name: Run Dockle agate
      #   run: ./dockle -af settings.py gisaia/stac-geodes:tests

  aias-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install test/requirements
      run: |
        pip install -r test/requirements.txt
    - name: Run  tests
      run: test/tests.sh

  geodes-stac-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install requirements-stac.txt
      run: |
        pip install -r requirements-stac.txt
    - name: Run  tests
      run: test/test_geodes_stac.sh

  