name: Run Trivy
run-name: Run Trivy - Vulnerability Scan

on:
  push:
  schedule:
    # At 05:15 UTC on day-of-month 2
    - cron: '15 5 2 * *'

jobs:
  trivy:
    name: Build and scan image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_name: [agate, airs, aproc-proc, aproc-service, stac-geodes, fam, arlas-fam-wui]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Build an image from Dockerfile ${{ matrix.image_name }}
      run: |
        docker build --build-arg version=${{ github.sha }} --platform "linux/amd64" -f docker/Dockerfile-${{ matrix.image_name }} -t gisaia/${{ matrix.image_name }}:${{ github.sha }} .

    - name: Run Trivy vulnerability scanner on ${{ matrix.image_name }}
      uses: aquasecurity/trivy-action@master
      env:
        TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2
        TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db:1
      with:
        image-ref: 'docker.io/gisaia/${{ matrix.image_name }}:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: false
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
        trivyignores: .github/workflows/.trivyignore
        scanners: 'vuln'
    - name: Notify Google Chat
      if: ${{ always() }} # Use always to ensure that the notification is also send on failure of former steps
      uses: SimonScholz/google-chat-action@main
      with:
        webhookUrl: '${{ secrets.GOOGLE_CHAT_SCAN_CHANEL }}'
        jobStatus: '${{ job.status }}'
        title: 'Trivy Scan on AIAS ${{ matrix.image_name }}'
